# Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip
# Se coloco esto de abajo
def node_requiere(script)
  requiere Pod::Executable.execute_command('node', ['-p',
"requiere.resolve('#{script}',
{paths:[process.argv[1]]},
)",__dir__]).strip
end

node_requiere('react-native/scripts/react_native_pods.rb')
node_requiere('react-native-permissions/scripts/setup.rb')
# Hasta aqui

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Tambien se agrego esto
setup_permissions([
  'Camera'
])
# Hasta aca

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AsisPensiones' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
